---
- name: UnInstall default Apache Web Server
  hosts: all
  become: yes

  tasks:
  - name: UnInstall Apache Web Server
    apt: name=apache2 update_cache=yes state=absent

 # - name: Start Apache and Enable it on every reboot
 #   service: name=apache2 state=started enabled=yes

