---
- hosts: all
  become: yes
  tasks:
  - name: install Docker                # install docker
    apt:
      name: docker.io
      state: present
      update_cache: true

  - name: install APT Transport HTTPS   # Устанавливает apt-transport-https, позволяя добавлять 
    apt:                                # внешние источники HTTPS в список источников APT
      name: apt-transport-https
      state: present

  - name: add Kubernetes apt-key        # Добавляет ключ apt-key репозитория Kubernetes APT для проверки ключей
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: add Kubernetes' APT repository       # Добавляет репозиторий Kubernetes APT в список источников APT 
    apt_repository:                            # ваших удаленных серверов
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'

  - name: install kubelet         # Устанавливает kubelet везде
    apt:
      name: kubelet
      state: present
      update_cache: true

  - name: install kubeadm         # Устанавливает kubeadm везде
    apt:
      name: kubeadm
      state: present

- hosts: STAGING_SERVERS          # # Устанавливает kubectl на мастере
  become: yes
  tasks:
  - name: install kubectl
    apt:
      name: kubectl
      state: present
      force: yes
