---
- name: Activation worker nodes
  hosts: master
  become: yes
  gather_facts: false

  tasks:
    - name: Get join command         # получает команду join, которую нужно запустить на рабочих узлах
      shell: kubeadm token create --print-join-command
      register: join_command_raw     # сохраняет в join_command_raw
    
    - name: Set join command         # созд новая переменная join_command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"
    - debug:
        var: join_command
    
    - name: create file1
      copy:
        dest: /home/user/ansible/file1.txt                 # create file1.txt
        content: "{{ join_command_raw.stdout_lines[0] }}"  # create content file1.txt

- name: worker servers
  hosts: worker
  become: yes

  tasks:
  - name: Ping
    ping:

  - name: init workers
    shell: "{{ hostvars[groups.master.0].join_command }} >> node_joined.txt"
    args:
      chdir: $HOME
      creates: node_joined.txt

    #- name: Message
    #- debug:
    #    msg: "{{ join_command_raw.stdout_lines[0] }} 
    #  delegate_to: k8s003, k8s004
