---
# handlers file for deploy_apache_web
- name: Restart Apache Debian             # restart apache for Debian
  service: name=apache2 state=restarted
  when: ansible_os_family == "Debian"

- name: Restart Apache RedHat             # restart apache for RedHat
  service: name=httpd state=restarted  
  when: ansible_os_family == "RedHat"
